### ISSUE TITLE
Chat/Dashboard: Players missing

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#516]
I have a situation: the players with ID 
76561198333756931 Lilith (LP)
76561198088775087 LimitlessDragon (In Chat human)
are not being recognized on the dashboard and then in the chat. In the Log files are the chats written down.

Lilith and LimitlessDragon are already on the dashboard but when online on the server, the dashboard wont pick them up

![image](https://github.com/gameserverapp/Platform/assets/99832504/450d7a78-5dab-4882-9ac7-9c1b364a7f6a)
![image](https://github.com/gameserverapp/Platform/assets/99832504/5956b97d-ef85-456a-9184-2cb1dd015ee1)
![image](https://github.com/gameserverapp/Platform/assets/99832504/d6c9b510-589c-4b1d-8b0d-8e5a1d0003de)

Those Screenshots were taken from the server 24120 / xhoqupald

The same is happening on my second server fjord 22805 / dqkfaymrd

![image](https://github.com/gameserverapp/Platform/assets/99832504/23f1c480-c641-446e-9cb6-4cae8ab5ee98)
![image](https://github.com/gameserverapp/Platform/assets/99832504/72eea949-e9ae-407f-abe5-3c60a749c11b)

the other player on that server is 
76561197989031056

And what's also strange is that the following player left the server a while ago

![image](https://github.com/gameserverapp/Platform/assets/99832504/93e205e0-6679-47ee-81bc-6a71be05a748)
![image](https://github.com/gameserverapp/Platform/assets/99832504/abe42e17-af39-45e2-98c7-9e4648134740)

Chat is sent properly throughout the cluster and discord for the people recognized by the Dashboard

I checked my servers over a different website where I can see, how many servers and players are online, and on that website, all players are listed correctly

The activity page from Fjoerd is nothing shown as an error
Same on Ragnarok after I reinstalled them on Saturday
This post is an addition to:
https://discord.com/channels/315049169071112193/945483534150303784/1157005292840685688

**Comment by mvaessen** [comment]
Hi, while I talked to you on Discord about the issue, i'll also post an update here in case people stumble upon this in the future.

The issue was caused by an FTP issue, which prevented GSA from downloading the character file. The issue wasn't being reported properly to the dashboard. This should now be fixed.

In addition will I also try to include a FTP test in the game server setup steps, to ensure the FTP setup was performed properly. Until now this hasn't been required since it seemed to work in most cases.

**Comment by LimitlessDrag0n** [comment]
The player Lilith, like mentioned above, is still not showing up in the chat, but on Dashboard

![image](https://github.com/gameserverapp/Platform/assets/99832504/1657e0bd-24ca-4720-8446-4f4f7716f113)
![image](https://github.com/gameserverapp/Platform/assets/99832504/659fdcdc-d302-43f8-9a83-208211781eec)

I joined the server today ( the new machine) I was immediately recognized by the dashboard and could send to chat. 

![image](https://github.com/gameserverapp/Platform/assets/99832504/43b09c5a-b1ad-4ed8-92ac-4f8673bc089b)

**Comment by mvaessen** [comment]
Hi, i was just looking at this. The character does seem to be present on the dashboard. Is this issue still active?

![Screenshot 2023-10-05 at 13 48 35](https://github.com/gameserverapp/Platform/assets/13402423/5e78625f-eabf-4a02-aba7-a9fdac4c3ec9)

**Comment by mvaessen** [comment]
I made some changes, please ask the player to talk in chat and see if it works this time :)

**Comment by LimitlessDrag0n** [comment]
Yes, this works! Thanks a lot!
